Metrics/BlockLength:
  Max: 50
  Exclude:
  - migrations/**/*.rb

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Style/IfUnlessModifier:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Alias:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
