Metrics/BlockLength:
  Max: 50
  Exclude:
  - migrations/**/*.rb

Metrics/MethodLength:
  Exclude:
  - app/fanalyze.rb

Style/IfUnlessModifier:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false
